[id]
  languageName = "Bahasa Indonesia"
  contentDir = "content/id"
  weight = 10
  [id.params]
    languageISO = "ID"
    languageTag = "id-ID"

[en]
  languageName = "English"
  contentDir = "content/en"
  weight = 15
  [en.params]
    languageISO = "EN"
    languageTag = "en-US"
