# Meta Data for SEO

## Homepage
title = "Sugeng Sulistiyawan"
titleSeparator = "-"
titleAddition = "Sugeng Sulistiyawan Portfolio"
description = "Mengalir Laksana Air, Menerjang Laksana Ombak."

## Documentation
# docsVersion = "0.3"

## Open Graph
images = ["og.png"]
ogLocale = "id_ID"
domainTLD = "sugeng-sulistiyawan.github.io"
titleHome = "Sugeng Sulistiyawan"

## Twitter Cards
twitterSite = ""
twitterCreator = ""

## JSON-LD
schemaType = "Person"
# schemaType = "Organization"
schemaName = "Sugeng Sulistiyawan Portfolio"
schemaAuthor = "Sugeng Sulistiyawan"
schemaAuthorTwitter = ""
schemaAuthorLinkedIn = "https://www.linkedin.com/in/sugengsulistiyawan"
schemaAuthorGitHub = "https://github.com/h-enk"
schemaLocale = "id-ID"
schemaLogo = "logo.png"
schemaLogoWidth = 512
schemaLogoHeight = 512
schemaImage = "og.png"
schemaImageWidth = 1280
schemaImageHeight = 640
schemaTwitter = ""
schemaLinkedIn = "https://www.linkedin.com/in/sugengsulistiyawan"
schemaGitHub = "https://github.com/sugeng-sulistiyawan"
schemaSection = "blog"

## Sitelinks Search Box
siteLinksSearchBox = false

## Chrome Browser
themeColor = "#5d2f86"

# Images
quality = 85
bgColor = "#fff"
landscapePhotoWidths = [900, 800, 700, 600, 500]
portraitPhotoWidths = [800, 700, 600, 500]
lqipWidth = "20x"
smallLimit = "300"

# Images
imageResponsive = true
imageConvertTo = "webp"
imageImageSizes = ["480","720","1080","1280","1600","2048"]
singleSize = false
imageAddClass = "img-fluid lazyload blur-up"

### Image template
defaultImage = "default-image.png" # put in `./assets/images/`
fillImage = "1270x740 Center" # normalize image size

# Footer
footer = "Powered by <a class=\"text-muted\" href=\"https://www.netlify.com/\" target=\"_blank\" rel=\"noopener\">Netlify</a>, <a class=\"text-muted\" href=\"https://gohugo.io/\" target=\"_blank\" rel=\"noopener\">Hugo</a>, and <a class=\"text-muted\" href=\"https://getdoks.org/\" target=\"_blank\" rel=\"noopener\">Doks</a>"

# Feed
copyRight = "Copyright © 2023 <a class=\"text-muted\" href=\"/\"><strong>Sugeng Sulistiyawan</strong></a>"

# Alert
alert = true
alertDismissable = false
# alertText = "Introducing the Doks child theme, several DX + UX updates, and more! <a class=\"alert-link stretched-link\" href=\"https://getdoks.org/blog/doks-v0.2/\" target=\"_blank\" rel=\"noopener\">Check out Doks v0.2</a>"
# alertText = "Hello, World! Memiliki IDE, Proyek dan ingin bekerjasama dengan saya? Langsung japri saya via <a class=\"alert-link stretched-link\" href=\"https://wa.me/62816658056\" target=\"_blank\" rel=\"noopener\">Whatsapp</a>!"

# Edit Page
# repoHost [Github | Gitea | GitLab | Bitbucket | BitbucketServer ] is used for building the edit link based on git hoster
repoHost = "GitHub"
#repoHost = "Gitea"
docsRepo = "https://github.com/sugeng-sulistiyawan/sugeng-sulistiyawan.github.io"
docsRepoBranch = "main"
docsRepoSubPath = ""
editPage = false
lastMod = false

[sections]
  sectionNav = ["docs", "guides"]

[options]
  lazySizes = true
  clipBoard = true
  instantPage = true
  flexSearch = true
  searchSectionsShow = []
  searchSectionsIndex = ["blog", "docs"]
  darkMode = true
  bootStrapJs = true
  breadCrumb = false
  highLight = true
  kaTex = false
  multilingualMode = true
  docsVersioning = false
  fullWidth = false
  navbarSticky = true
  toTopButton = false
  scrollSpy = true # experimental; needs Bootstrap >= 5.2.0-beta1

[menu]
  [menu.section]
    auto = true
    collapsibleSidebar = true
