# Meta Data for SEO

## Homepage
title = "Sugeng Sulistiyawan"
titleSeparator = "-"
titleAddition = "Sugeng Sulistiyawan Portfolio"
description = "Always Learning and Keep Learning."

## Documentation
# docsVersion = "0.3"

## Open Graph
images = ["og.png"]
ogLocale = "en_US"
domainTLD = "sugengsulistiyawan.my.id"
titleHome = "Sugeng Sulistiyawan"

## Twitter Cards
twitterSite = ""
twitterCreator = ""

## JSON-LD
schemaType = "Person"
# schemaType = "Organization"
schemaName = "Sugeng Sulistiyawan Portfolio"
schemaAuthor = "Sugeng Sulistiyawan"
schemaAuthorTwitter = ""
schemaAuthorLinkedIn = "https://www.linkedin.com/in/sugengsulistiyawan"
schemaAuthorGitHub = "https://github.com/sugeng-sulistiyawan"
schemaLocale = "en-US"
schemaLogo = "logo.png"
schemaLogoWidth = 512
schemaLogoHeight = 512
schemaImage = "og.png"
schemaImageWidth = 1280
schemaImageHeight = 640
schemaTwitter = ""
schemaLinkedIn = "https://www.linkedin.com/in/sugengsulistiyawan"
schemaGitHub = "https://github.com/sugeng-sulistiyawan"
schemaSection = "blog"

## Sitelinks Search Box
siteLinksSearchBox = true

## Chrome Browser
themeColor = "#5d2f86"

# Images
quality = 85
bgColor = "#fff"
landscapePhotoWidths = [900, 800, 700, 600, 500]
portraitPhotoWidths = [800, 700, 600, 500]
lqipWidth = "20x"
smallLimit = "300"

# Images
imageResponsive = true
imageConvertTo = "webp"
imageImageSizes = ["480","720","1080","1280","1600","2048"]
singleSize = false
imageAddClass = "img-fluid lazyload blur-up"

### Image template
defaultImage = "default-image.png" # put in `./assets/images/`
fillImage = "1270x740 Center" # normalize image size

# Footer
footer = "Powered by <a class=\"text-muted\" href=\"https://www.netlify.com/\" target=\"_blank\" rel=\"noopener\">Netlify</a>, <a class=\"text-muted\" href=\"https://gohugo.io/\" target=\"_blank\" rel=\"noopener\">Hugo</a>, and <a class=\"text-muted\" href=\"https://getdoks.org/\" target=\"_blank\" rel=\"noopener\">Doks</a>"

# Feed
copyRight = "Copyright © 2023 Sugeng Sulistiyawan"

# Alert
alert = true
alertDismissable = false
# alertText = "Introducing the Doks child theme, several DX + UX updates, and more! <a class=\"alert-link stretched-link\" href=\"https://getdoks.org/blog/doks-v0.2/\" target=\"_blank\" rel=\"noopener\">Check out Doks v0.2</a>"
# alertText = "Hello, World! Memiliki IDE, Proyek dan ingin bekerjasama dengan saya? Langsung japri saya via <a class=\"alert-link stretched-link\" href=\"https://wa.me/62816658056\" target=\"_blank\" rel=\"noopener\">Whatsapp</a>!"

# Edit Page
# repoHost [Github | Gitea | GitLab | Bitbucket | BitbucketServer ] is used for building the edit link based on git hoster
repoHost = "GitHub"
#repoHost = "Gitea"
docsRepo = "https://github.com/sugeng-sulistiyawan/sugeng-sulistiyawan.github.io"
docsRepoBranch = "main"
docsRepoSubPath = ""
editPage = true
lastMod = true

[sections]
  sectionNav = ["docs", "guides"]

[options]
  lazySizes = true
  clipBoard = true
  instantPage = false
  flexSearch = true
  searchSectionsShow = []
  searchSectionsIndex = ["blog", "docs"]
  darkMode = true
  bootStrapJs = true
  breadCrumb = false
  highLight = true
  kaTex = false
  multilingualMode = true
  docsVersioning = false
  fullWidth = false
  navbarSticky = true
  toTopButton = false
  scrollSpy = true # experimental; needs Bootstrap >= 5.2.0-beta1

[menu]
  [menu.section]
    auto = true
    collapsibleSidebar = true

[[social]]
  name = "Email"
  label = "sugeng.sulistiyawan@gmail.com"
  icon = '<svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-mail"><path d="M4 4h16c1.1 0 2 .9 2 2v12c0 1.1-.9 2-2 2H4c-1.1 0-2-.9-2-2V6c0-1.1.9-2 2-2z"></path><polyline points="22,6 12,13 2,6"></polyline></svg>'
  url = "mailto:sugeng.sulistiyawan@gmail.com"
  nav = false
  weight = 10

# [[social]]
#   name = "HP/Whatsapp"
#   label = "+62 816 658 056"
#   icon = '<svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-phone"><path d="M22 16.92v3a2 2 0 0 1-2.18 2 19.79 19.79 0 0 1-8.63-3.07 19.5 19.5 0 0 1-6-6 19.79 19.79 0 0 1-3.07-8.67A2 2 0 0 1 4.11 2h3a2 2 0 0 1 2 1.72 12.84 12.84 0 0 0 .7 2.81 2 2 0 0 1-.45 2.11L8.09 9.91a16 16 0 0 0 6 6l1.27-1.27a2 2 0 0 1 2.11-.45 12.84 12.84 0 0 0 2.81.7A2 2 0 0 1 22 16.92z"></path></svg>'
#   url = "https://wa.me/62816658056"
#   nav = true
#   weight = 15

[[social]]
  name = "LinkedIn"
  label = "@sugengsulistiyawan"
  icon = '<svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-linkedin"><path d="M16 8a6 6 0 0 1 6 6v7h-4v-7a2 2 0 0 0-2-2 2 2 0 0 0-2 2v7h-4v-7a6 6 0 0 1 6-6z"></path><rect x="2" y="9" width="4" height="12"></rect><circle cx="4" cy="4" r="2"></circle></svg>'
  url = "https://www.linkedin.com/in/sugengsulistiyawan"
  nav = true
  weight = 20

[[social]]
  name = "Instagram"
  label = "@sugengsulistiyawan"
  icon = '<svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-instagram"><rect x="2" y="2" width="20" height="20" rx="5" ry="5"></rect><path d="M16 11.37A4 4 0 1 1 12.63 8 4 4 0 0 1 16 11.37z"></path><line x1="17.5" y1="6.5" x2="17.51" y2="6.5"></line></svg>'
  url = "https://www.instagram.com/sugengsulistiyawan"
  nav = false
  weight = 25

[[social]]
  name = "Facebook"
  label = "@sugeng.sulistiyawan"
  icon = '<svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-facebook"><path d="M18 2h-3a5 5 0 0 0-5 5v3H7v4h3v8h4v-8h3l1-4h-4V7a1 1 0 0 1 1-1h3z"></path></svg>'
  url = "https://www.facebook.com/sugeng.sulistiyawan"
  nav = false
  weight = 26

[[social]]
  name = "GitHub"
  label = "@sugeng-sulistiyawan"
  icon = '<svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-github"><path d="M9 19c-5 1.5-5-2.5-7-3m14 6v-3.87a3.37 3.37 0 0 0-.94-2.61c3.14-.35 6.44-1.54 6.44-7A5.44 5.44 0 0 0 20 4.77 5.07 5.07 0 0 0 19.91 1S18.73.65 16 2.48a13.38 13.38 0 0 0-7 0C6.27.65 5.09 1 5.09 1A5.07 5.07 0 0 0 5 4.77a5.44 5.44 0 0 0-1.5 3.78c0 5.42 3.3 6.61 6.44 7A3.37 3.37 0 0 0 9 18.13V22"></path></svg>'
  url = "https://github.com/sugeng-sulistiyawan"
  nav = true
  weight = 30

[[social]]
  name = "Gitlab"
  label = "@sugeng-sulistiyawan"
  icon = '<svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-gitlab"><path d="M22.65 14.39L12 22.13 1.35 14.39a.84.84 0 0 1-.3-.94l1.22-3.78 2.44-7.51A.42.42 0 0 1 4.82 2a.43.43 0 0 1 .58 0 .42.42 0 0 1 .11.18l2.44 7.49h8.1l2.44-7.51A.42.42 0 0 1 18.6 2a.43.43 0 0 1 .58 0 .42.42 0 0 1 .11.18l2.44 7.51L23 13.45a.84.84 0 0 1-.35.94z"></path></svg>'
  url = "https://gitlab.com/sugeng-sulistiyawan"
  nav = false
  weight = 40

[[social]]
  name = "Youtube"
  label = "@SugengSulistiyawan"
  icon = '<svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-youtube"><path d="M22.54 6.42a2.78 2.78 0 0 0-1.94-2C18.88 4 12 4 12 4s-6.88 0-8.6.46a2.78 2.78 0 0 0-1.94 2A29 29 0 0 0 1 11.75a29 29 0 0 0 .46 5.33A2.78 2.78 0 0 0 3.4 19c1.72.46 8.6.46 8.6.46s6.88 0 8.6-.46a2.78 2.78 0 0 0 1.94-2 29 29 0 0 0 .46-5.25 29 29 0 0 0-.46-5.33z"></path><polygon points="9.75 15.02 15.5 11.75 9.75 8.48 9.75 15.02"></polygon></svg>'
  url = "https://www.youtube.com/c/SugengSulistiyawan"
  nav = false
  weight = 50
