[[main]]
  name = "Tentang Saya"
  url = "/about/"
  weight = 10

[[main]]
  name = "CV"
  url = "/sugeng_sulistiyawan_resume.pdf"
  weight = 100

[[main]]
  name = "Blog"
  url = "/blog/"
  weight = 20

[[main]]
  name = "Open Source"
  identifier = "opensource"
  url = "/docs/opensource"
  weight = 30

[[main]]
  name = "Yii2 Framework"
  url = "/docs/opensource/yii2/"
  weight = 40
  parent = "opensource"

[[main]]
  name = "Lainnya"
  url = "/docs/opensource/other/"
  weight = 99
  parent = "opensource"


# [[main]]
#   name = "Tutorial"
#   weight = 50
#   identifier = "tutorial"
#   url = "https://getdoks.org/tutorial/introduction/"
#   parent = "opensource"

# [[footer]]
#   name = "Privacy"
#   url = "/privacy-policy/"
#   weight = 10
