[[main]]
  name = "Tentang"
  url = "/about/"
  weight = 10

[[main]]
  name = "Kontak"
  url = "/contact/"
  weight = 15

[[main]]
  name = "Blog"
  url = "/blog/"
  weight = 20

[[main]]
  name = "Open Source"
  weight = 30
  identifier = "opensource"
  url = "/docs/opensource"

[[main]]
  name = "Yii2 Framework"
  weight = 40
  identifier = "opensource-yii2"
  url = "/docs/opensource/yii2/"
  parent = "opensource"

# [[main]]
#   name = "Tutorial"
#   weight = 50
#   identifier = "tutorial"
#   url = "https://getdoks.org/tutorial/introduction/"
#   parent = "opensource"

# [[footer]]
#   name = "Privacy"
#   url = "/privacy-policy/"
#   weight = 10
